### ISSUE TITLE
Running into error when running train_cnn_lateral_mov3.py

### ISSUE THREAD

**Issue by Blaise-g** [Zyj061/retina-crnn_model#1]
Hello, I am having trouble performing the training of the CNN model for natural scenes movie 2. As I do not have access to how the dataset with the frames and labels is preprocessed I think it might have to do with that.

I was wondering if you could kindly share a code snippet with how and in which way you extract the frames and labels from the dataset indicated in the paper (respectively video frames from movie 2 and neuronal recordings evoked when watching the same movie) or possibly the fully trained CRNN model with weights.

I would like to thank you in advance for your time.

**Comment by Zyj061** [comment]
Hi, we have updated our codes and the corresponding ·readme.md`. you can run the given example commans to reproduce our experiments. Otherwise, can you provide a little more information on the way you running the script? Information that would be helpful for me to assist:
```
1. Specific commands sent to the script
2. The full traceback

**Comment by Blaise-g** [comment]
Thank you very much, all much clearer now.
