### ISSUE TITLE
About generating the dataset

### ISSUE THREAD

**Issue by haowuxc** [Zyj061/retina-crnn_model#2]
Hi! I read the paper seriously about the RGC data but don't find the way to generate the dataset in the source code. So I am seeking help here.
The model is trained with the response of 80 RGCs. However, there are 38/49 RGCs found in different retina. Besises, there are 1800 frames and 1600 frames in movie1 and movie2 respectively. A single frame will display about 33 ms in front of the retina. But there are only responding neural activity of 60 scenes of length 300 ms offered in the response of RGC data. So I am confused about how the 60 sences are selected? The orginal paper gives the method but I can not find the final selected scenes?
So can you offer more details about how to generate the dataset used in your code or offer the dataset directly? 

Thanks!

**Comment by Blaise-g** [comment]
Have run into the same problem :)

If you could offer more details concerning the dataset generation starting from the original referenced dataset ( in the paper would be great.

Thank you!

**Comment by Zyj061** [comment]
Hello, we have updated the code and provided some trained models and test data of movie2. You can run `test_models.py` to test our models. If you want to know how to train the network, you can refer to the `train_off_cnn.py`. The `off_data_generator.py` and `data_generator.py`  are scripts for preprocessing data.

**Comment by haowuxc** [comment]
Hi, data_generator.py needs train/test_mov1k.hdf5 and train/test_mov3.hdf5 files, but I only find test_mov3.hdf5 files in data folder, which is not enough for training. Actually, I just want to know how the frames and responses of movie are aligned because a single frame will display about 33 ms in front of the retina and there are 1800 frames and 1600 frames in movie1 and movie2 respectively. But the response just has 18000 ms.

**Comment by Zyj061** [comment]
The trained models are trained on movie2.  The test code we provide use `test_mov3.hdf5`, not `test_mov1k.hdf5`. 
The response corresponding to each frame is that the number of spikes fired by the RGC when each frame is displayed (about 33ms). If you want to know how to train network, you can see the train_off_cnn.py provided, the training data and data pre-processing code required have been provided.

**Comment by haowuxc** [comment]
> The trained models are trained on movie2. The test code we provide use `test_mov3.hdf5`, not `test_mov1k.hdf5`. The response corresponding to each frame is that the number of spikes fired by the RGC when each frame is displayed (about 33ms). If you want to know how to train network, you can see the train_off_cnn.py provided, the training data and data pre-processing code required have been provided.

I mean that a frame displays about 33ms, so 1800/1600 frames will have a response with 1800/1600 * 33ms = 59400/52800 ms. But in the response I find the max spike time is 18000 ms. So I doubt not all frames are displayed to the retina. Can you explain the relationship between the 1800/1600 frames and 18000 ms response? Thanks!
